<?php
/**
 * @file
 * Handle installation and un-installation of the module.
 */

 /**
 * Move settings from variables to config.
 */
function og_menu_default_links_update_1000() {
  // Migrate variables to config.
  $config = config('og_menu_default_links.settings');
  $config->set('og_menu_default_links_module', update_variable_get('og_menu_default_links_module', 'og_menu'));
  $config->save();

  // Delete variables.
  update_variable_del('og_menu_default_links_module');
}
